VIPCourse/xfzes/xfz/apps/course/urls.py
#coding=utf-8
from django.urls import path
from . import views
app_name = 'course'
urlpatterns = [
    path('',views.course_index,name='course_index'),
    path('<course_id>/',views.course_detail,name='course_detail'),
    path('', views.course_index, name='course_index'),
    path('<int:course_id>/', views.course_detail, name='course_detail'),
    path('course_order/<int:course_id>/', views.course_order, name='course_order'),
    path('course_order_key/', views.course_order_key, name="course_order_key"),
    path('notify_view/', views.notify_view, name='notify_view')
]

VIPCourse/xfzes/xfz/apps/payinfo/urls.py
#encoding: utf-8

from django.urls import path
from . import views

app_name = 'payinfo'

urlpatterns = [
    path('',views.index,name='index'),
    # path('notify_url/',views.notify_view,name='notify_view'),
    # path('download/',views.download,name='download')
]

VIPCourse/xfzes/xfz/apps/xfzauth/urls.py
#coding=utf-8
from django.urls import path
from . import views

app_name = 'xfzauth'


urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('img_captcha/',views.img_captcha,name='img_captcha'),
    path('sms_captcha/',views.sms_captcha,name='sms_captcha'),
    path('cache/',views.cache_test,name='cache'),
    path('register/',views.register,name='register')
]

VIPCourse/xfzes/xfz/xfz/urls.py
from django.urls import path,include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.index,name='index'),
    path('news/', include("apps.news.urls")),
    path('cms/',include("apps.cms.urls")),
    path('account/',include("apps.xfzauth.urls")),
    path('course/',include("apps.course.urls")),
    path('ueditor/',include("apps.ueditor.urls")),
    path('payinfo/',include("apps.payinfo.urls")),
    # path('search/',views.search,name='search'),使用whoosh
    path('search/',include('haystack.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/",include(debug_toolbar.urls)))

VIPCourse/xfzes/xfz/front/templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
    
    {% endblock %}</title>
    <link rel="stylesheet" href="{% static '/css/common/auth.min.css'%}">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_970281_o5k3j2mbfft.css">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/message.min.js'%}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <script src="{% static 'js/front_base.min.js' %}"></script>

    {% block head %}
    
    {% endblock %}
</head>
<body>
    {% csrf_token %}
    <header class="header">
        <div class="container">
            <div class="logo-box">
                <a href="/"></a> <!--a标签是行内元素，里面没有内容的话，宽度和高度都是为0-->
            </div>
            <ul class="nav">
                <li><a href="/" >创业资讯</a></li>
                <li><a href="{% url 'course:course_index' %}">创业课堂</a></li>
                <li><a href="{% url 'payinfo:index' %}">付费咨询</a></li>
                <li><a href="/search/">搜索</a></li>
            </ul>
            <div class="auth-box">
                <i class="icon-person iconfont" ></i>
                {% if user.is_authenticated %}
                    <a href="#" class="authenticated-box">{{ user.username }}</a>
                    <div class="user-more-box">
                        <i class="triangle"></i>
                        {% if user.is_staff %}
                        <a href="{% url 'cms :index' %}">管理系统</a>
                        {% endif %}
                        <a href="{% url 'xfzauth:logout'%}">退出登录</a>
                    </div>
                {% else %}
                    <a href="#" class="signin-btn">登录</a> /
                    <a href="#" class="signup-btn">注册</a>
                {% endif %}

            </div>
        </div>
    </header>
    {% block main %}{% endblock %}

    <footer class="footer">
        <div class="top-group">
            <div class="top-inner-group">
                <div class="logo-box">

                </div>
                <div class="detail-group">
                    <div class="line1">
                        <ul class="links">
                            <li><a href="#">关于小饭桌</a></li>
                            <li><a href="#">创业课堂</a></li>
                            <li><a href="#">寻求报道</a></li>
                            <li><a href="#">创业礼包</a></li>
                        </ul>
                        <div class="about-us">
                            <span class="title">关于我们：</span>
                            <ul class="social-group">
                                <li class="weixin">
                                    <span class="text">ljc007</span>
                                    <div class="wx-qrcode">

                                    </div>
                                </li>
                                <li class="weibo">
                                    <a class="text" href="#">猎鲸船起航</a>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="line2">
                        <p class="address">地址：浙江省杭州市西湖区文新街道五联西苑201</p>
                        <p class="content">联系方式：18367150862</p>
                    </div>
                </div>
            </div>

        </div>
        <div class="bottom-group">
            @杭州猎鲸船投资有限公司 浙ICP备17089840-1
        </div>
    </footer>
    <div class="mask-wrapper">
        <div class="auth-wrapper">
            <div class="close-wrapper">
                <span class="close-btn icon-Close iconfont"></span>
            </div>
             <div class="auth-inner-wrapper">
                 <div class="scrool-wrapper">
                    <div class="signin-group auth-group">
                        <div class="top-group">
                            <span class="title">请登录</span>
                            <a href="javascript:void(0);" class="switch">立即注册></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password" placeholder="请输入密码">
                            </div>
                            <div class="input-group">
                                <label class="remember-label">
                                    <input type="checkbox" name="remember" value="1">记住我
                                </label>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即登录">
                            </div>
                        </div>

                    </div>
                    <div class="signup-group auth-group">
                        <div class="top-group">
                            <span class="title">请注册</span>
                            <a href="javascript:void(0);" class="switch">立即登录></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone"placeholder="请输入手机号码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="username"placeholder="请输入用户名">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">
                                </div>
                                <div class="input-group-addon">
                                    <img src="{% url 'xfzauth:img_captcha'%}" alt="" class="img-captcha" style="cursor: pointer">
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password1" placeholder="请输入密码">
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password2" placeholder="请再次输入密码">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="sms_captcha" placeholder="请输入短信验证码">
                                </div>
                                <div class="input-group-addon">
                                    <span class="sms-captcha-btn">发送验证码</span>
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="submit"class="submit-btn"value="立即注册">
                            </div>
                        </div>
                    </div>
                 </div>

             </div>
        </div>
    </div>

</body>

</html>